### ISSUE TITLE
Pusher channels for creating traffic monitor showing error

### ISSUE THREAD

**Issue by linuxbiekaisar** [SchoolOfFreelancing/Back-Office#10]
During creating a traffic monitor pusher channel showing this error and failed to fixed.
![Screenshot from 2020-07-27 17-37-32](https://user-images.githubusercontent.com/60579529/88537884-338b5b80-d030-11ea-8992-6f8ee0169c29.png)
![Uploading Screenshot from 2020-07-27 17-38-00.png…]()

**Comment by AnythingLinux** [comment]
use python 3.x and try again

**Comment by AnythingLinux** [comment]
it has been a while not get any response. closing issue how ever do not hesitated to re open this issue if your problem not fixed
