### ISSUE TITLE
MySQL BUG for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by ThinkLikeLinux** [SchoolOfFreelancing/Back-Office#12]
MySQL BUG for Ubuntu 20.04 LTS

https://bugs.mysql.com/bug.php?id=100188

**Comment by AnythingLinux** [comment]
@ThinkLikeLinux follow this into fresh system https://www.fosstechnix.com/how-to-install-mysql-5-7-on-ubuntu-20-04-lts/

Let me know if its works for you.

**Comment by AnythingLinux** [comment]
@ThinkLikeLinux write down workaround if you can overcome this BUG and this may happens when a OS update but vendor software does not update their software also.

**Comment by AnythingLinux** [comment]
@ThinkLikeLinux this process worked for me Ubuntu 20.04

sudo -i
apt update
apt install mysql-server
mysql_secure_installation
nano /etc/mysql/mysql.conf.d/mysqld.cnf
#And then change the bind-address line to 0.0.0.0
# Save and exit

ufw allow from any to any port 3306 proto tcp
sudo systemctl restart mysql
sudo systemctl enable mysql

sudo mysql
CREATE DATABASE mydb;
CREATE USER 'masum'@'localhost' IDENTIFIED WITH mysql_native_password BY '01722G@usia';
ALTER USER 'masum'@'localhost' IDENTIFIED WITH mysql_native_password BY '01722G@usia';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT on *.* TO 'masum'@'localhost' WITH GRANT OPTION;
use mydb;
FLUSH PRIVILEGES;
exit
mysql -u masum -p
# use pass 01722G@usia for login


https://gist.github.com/UbuntuEvangelist/2ad145d276e23ade663f36cbbed067bb
