### ISSUE TITLE
MySQL db failed to start during Mautic installation

### ISSUE THREAD

**Issue by LinuxlinkedBD** [SchoolOfFreelancing/Back-Office#13]
hello, i am facing MySQL db failure issue during Mautic installation

(1) When i installed Mautic first time, there was no issue on MySQL DB but Mautic installation was getting failed in step 2, i,e: after putting user name and password in http://localhost/installer/step/2 i was getting "site is offline_500 internal server error". this was the log from /var/log/apache2 :

[Tue Oct 06 12:54:25.015591 2020] [php7:error] [pid 5629] [client 127.0.0.1:36798] PHP Fatal error:  require(): Failed opening required '/var/www/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/usr/share/php') in /var/www/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209, referer: http://localhost/installer/step/2

i could not figure out any solution from the above error and then decided to go for another fresh installation.

(2) Now, when i am trying to install MySQL db this time it is showing the below error:
$  sudo mysql_secure_installation
Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
$ systemctl start mysql.service
Failed to start mysql.service: Access denied
See system logs and 'systemctl status mysql.service' for details.

$ systemctl status mysql.service
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-10-19 22:40:56 +06; 1min 3s ago
  Process: 3261 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=1/FAILURE)

**Comment by AnythingLinux** [comment]
https://gist.github.com/UbuntuEvangelist/2f20f07eb692f6fd81827f5332922283

follow this into fresh system. let me know if its work for you
