### ISSUE TITLE
trape not installing on ubuntu18.04lts due to pyhon version conflicts

### ISSUE THREAD

**Issue by kngvamxx** [SchoolOfFreelancing/Back-Office#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kngvamxx** [comment]
![Uploading gg.png…]()

**Comment by AnythingLinux** [comment]
use this trap with python 3.x into Ubuntu 20.04 LTS https://github.com/jofpin/trape
