### ISSUE TITLE
mautic bug problem

### ISSUE THREAD

**Issue by LinuxPlaner** [SchoolOfFreelancing/Back-Office#20]
![Screenshot from 2021-01-19 23-32-48](https://user-images.githubusercontent.com/69644107/105072098-a3dedb00-5aaf-11eb-887e-81f0b67cb2a6.png)

**Comment by badhonhitech** [comment]
same here

https://github.com/mautic/mautic/issues/

**Comment by DevOpsEvangelist** [comment]
same here
