### ISSUE TITLE
Having issue on Drupal installation 

### ISSUE THREAD

**Issue by LinauxTerminology** [SchoolOfFreelancing/Back-Office#21]
I have installation problem on Drupal session. please review 

![Screenshot from 2021-01-26 08-41-31](https://user-images.githubusercontent.com/74730192/105852619-b165fa80-5fb2-11eb-8cc2-01267837590e.png)

**Comment by AnythingLinux** [comment]
follow this https://gist.github.com/UbuntuEvangelist/9e396842641104bc029beb8e560f18bc
