### ISSUE TITLE
OpenVas 9 || warning secinfo database missing 

### ISSUE THREAD

**Issue by LinuxlinkedBD** [SchoolOfFreelancing/Back-Office#26]
After OpenVas9 installation, there is **warning: secinfo database missing** .
Probably the casue is below command output:

`amin@cli:~$ sudo greenbone-nvt-sync
--2021-03-17 22:23:36--  http://dl.greenbone.net/community-nvt-feed-current.tar.bz2
Resolving dl.greenbone.net (dl.greenbone.net)... 89.146.224.58, 2a01:130:2000:127::d1
Connecting to dl.greenbone.net (dl.greenbone.net)|89.146.224.58|:80... failed: Connection timed out.
Connecting to dl.greenbone.net (dl.greenbone.net)|2a01:130:2000:127::d1|:80... failed: Network is unreachable.

amin@cli:~$ sudo greenbone-scapdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

amin@cli:~$ sudo greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]`

**Comment by LinuxlinkedBD** [comment]
![image](https://user-images.githubusercontent.com/70909031/111661492-41008a80-8839-11eb-8a7b-bf120f98261b.png)

**Comment by zer0matt** [comment]
Same here, whenever I try to run those commands I get the same errors, I'll let you know if I can fix it
