### ISSUE TITLE
Harakka session

### ISSUE THREAD

**Issue by LinuxDevOpsGirl** [SchoolOfFreelancing/Back-Office#5]
Harakka is not working
Haraka cannot be opened on localhost

**Comment by AnythingLinux** [comment]
@LinuxDevOpsGirl Install Haraka’s node.js dependencies locally:

$ npm install
Edit config/plugins and config/smtp.ini to specify the plugins and config you want.

Finally run Haraka:

$ node haraka.js

**Comment by AnythingLinux** [comment]
harakka require a cloud Linux server and a domain for complete setup including SMTP. If you have all you can do this job into cloud linux or you can do

Apache Fineract is a Platform for Digital Financial Services and its open source software for financial services.

Fineract provides a reliable, robust, and affordable solution for entrepreneurs, financial institutions, and service providers to offer financial services to the world’s 2 billion underbanked and unbanked. Fineract is aimed at innovative mobile and cloud-based solutions, and enables digital transaction accounts for all.

Fineract 1.x is a mature platform with open APIs, while Fineract CN is a cloud native, microservice architecture also supporting open banking APIs. Into this sesison you will setup Apache Fineract using Docker and Docker compose from GitHub: https://github.com/apache/fineract
