### ISSUE TITLE
Apache Fintech have Docker SSL Handshake Error

### ISSUE THREAD

**Issue by rakibulinux** [SchoolOfFreelancing/Back-Office#8]
We are not able to install apache fintech on our Ubuntu Masing using Docker. It shows us Docker SSL Handshake Error.

**Comment by AnythingLinux** [comment]
@rakibulinux added cocorico into training pipeline. removed apache Finertec

**Comment by AnythingLinux** [comment]
**workaround** 

# setup Java >= 11 (OpenJDK JVM)
# setup MySQL
# setup docker
# setup docker compose
# clone Apache Fineract from github
# Deploy

# docker Install
sudo -i
apt update
apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
apt update
apt install docker-ce -y
systemctl status docker
docker --version

# Docker-compose install

sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
docker-compose --version

# Apache fineract
sudo -i
git clone https://github.com/apache/fineract.git
cd fineract
docker pull apache/fineract
docker-compose build
docker-compose up -d

Visit: http://localhost:9090/?baseApiUrl=https://localhost:8443/fineract-provider&tenantIdentifier=default


https://gist.github.com/UbuntuEvangelist/68e1c80b7717be6b9b3add86a863ae24
