### ISSUE TITLE
Unable to install Vapor on Ubuntu 18.04

### ISSUE THREAD

**Issue by afahitech** [SchoolOfFreelancing/Back-Office#9]
![Screenshot from 2020-06-02 23-34-39](https://user-images.githubusercontent.com/57868100/84063212-8490b300-a9e2-11ea-8c6c-3435c31fc637.png)

Unable to install vapor !!

**Comment by AnythingLinux** [comment]
This task has been removed from training pipeline for dependency problem. Added Siberian CMS and happy to close this issue !

https://docs.google.com/document/d/1p6g5F7-S2W2jI6WEvH_wxj1vYkA8jbl0v9cuYpYUfTQ/edit?usp=sharing
